gitops-runtime:
  global:
    codefresh:
      accountId: 67e0b4dd3af507ee136b4718
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
      isConfigurationRuntime: true
